package io.github.connellite.jdbc;

import io.github.connellite.jdbc.internal.ColonPrefixSqlParser;
import io.github.connellite.jdbc.internal.ParsedParameters;
import io.github.connellite.jdbc.internal.ParsedSql;
import io.github.connellite.jdbc.internal.SqlParser;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLType;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * PreparedStatement wrapper with named parameters (e.g. {@code :id}).
 * Internally converts SQL to positional placeholders ({@code ?}) for drivers
 * that only support JDBC positional parameters.
 */
@SuppressWarnings({"UnusedReturnValue", "MagicConstant"})
public final class NamedPreparedStatement implements AutoCloseable {
    private static final SqlParser SQL_PARSER = new ColonPrefixSqlParser();

    private final PreparedStatement statement;
    private final ParsedSql parsedSql;
    private final Map<String, List<Integer>> namedIndexes;
    private final Set<String> boundValues = new HashSet<>();

    /**
     * Creates a named-parameter statement and compiles SQL to JDBC positional placeholders.
     *
     * @param connection JDBC connection used to create underlying prepared statement
     * @param sql SQL with named parameters (for example {@code :id})
     */
    public NamedPreparedStatement(Connection connection, String sql) throws SQLException {
        this(connection, sql, Connection::prepareStatement);
    }

    /**
     * Creates a named-parameter statement and requests auto-generated keys behavior.
     */
    public NamedPreparedStatement(Connection connection, String sql, int autoGeneratedKeys) throws SQLException {
        this(connection, sql, (conn, parsed) -> conn.prepareStatement(parsed, autoGeneratedKeys));
    }

    /**
     * Creates a named-parameter statement with a target result-set type and concurrency.
     */
    public NamedPreparedStatement(Connection connection, String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        this(connection, sql, (conn, parsed) -> conn.prepareStatement(parsed, resultSetType, resultSetConcurrency));
    }

    /**
     * Creates a named-parameter statement with result-set type, concurrency and holdability.
     */
    public NamedPreparedStatement(Connection connection, String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        this(connection, sql, (conn, parsed) -> conn.prepareStatement(parsed, resultSetType, resultSetConcurrency, resultSetHoldability));
    }

    /**
     * Creates a named-parameter statement and requests generated keys by column indexes.
     */
    public NamedPreparedStatement(Connection connection, String sql, int[] columnIndexes) throws SQLException {
        this(connection, sql, (conn, parsed) -> conn.prepareStatement(parsed, columnIndexes));
    }

    /**
     * Creates a named-parameter statement and requests generated keys by column names.
     */
    public NamedPreparedStatement(Connection connection, String sql, String[] columnNames) throws SQLException {
        this(connection, sql, (conn, parsed) -> conn.prepareStatement(parsed, columnNames));
    }

    private NamedPreparedStatement(Connection connection, String sql, PreparedStatementCreator statementCreator) throws SQLException {
        Objects.requireNonNull(connection, "connection");
        this.parsedSql = SQL_PARSER.parse(sql);
        this.namedIndexes = indexNamedParameters(parsedSql.parameters());
        this.statement = statementCreator.create(connection, parsedSql.sql());
    }

    /**
     * Static factory for {@link NamedPreparedStatement}.
     */
    public static NamedPreparedStatement of(Connection connection, String sql) throws SQLException {
        return new NamedPreparedStatement(connection, sql);
    }

    /**
     * Static factory for {@link NamedPreparedStatement} with auto-generated keys behavior.
     */
    public static NamedPreparedStatement of(Connection connection, String sql, int autoGeneratedKeys) throws SQLException {
        return new NamedPreparedStatement(connection, sql, autoGeneratedKeys);
    }

    /**
     * Static factory for {@link NamedPreparedStatement} with result-set type and concurrency.
     */
    public static NamedPreparedStatement of(Connection connection, String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return new NamedPreparedStatement(connection, sql, resultSetType, resultSetConcurrency);
    }

    /**
     * Static factory for {@link NamedPreparedStatement} with result-set type, concurrency and holdability.
     */
    public static NamedPreparedStatement of(Connection connection, String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new NamedPreparedStatement(connection, sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    /**
     * Static factory for {@link NamedPreparedStatement} requesting generated keys by column indexes.
     */
    public static NamedPreparedStatement of(Connection connection, String sql, int[] columnIndexes) throws SQLException {
        return new NamedPreparedStatement(connection, sql, columnIndexes);
    }

    /**
     * Static factory for {@link NamedPreparedStatement} requesting generated keys by column names.
     */
    public static NamedPreparedStatement of(Connection connection, String sql, String[] columnNames) throws SQLException {
        return new NamedPreparedStatement(connection, sql, columnNames);
    }

    /**
     * Binds object value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setObject(String name, Object value) throws SQLException {
        return setByIndex(name, index -> statement.setObject(index, value));
    }

    /**
     * Binds int value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setInt(String name, int value) throws SQLException {
        return setByIndex(name, index -> statement.setInt(index, value));
    }

    /**
     * Binds long value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setLong(String name, long value) throws SQLException {
        return setByIndex(name, index -> statement.setLong(index, value));
    }

    /**
     * Binds string value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setString(String name, String value) throws SQLException {
        return setByIndex(name, index -> statement.setString(index, value));
    }

    /**
     * Binds boolean value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setBoolean(String name, boolean value) throws SQLException {
        return setByIndex(name, index -> statement.setBoolean(index, value));
    }

    /**
     * Binds byte value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setByte(String name, byte value) throws SQLException {
        return setByIndex(name, index -> statement.setByte(index, value));
    }

    /**
     * Binds short value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setShort(String name, short value) throws SQLException {
        return setByIndex(name, index -> statement.setShort(index, value));
    }

    /**
     * Binds float value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setFloat(String name, float value) throws SQLException {
        return setByIndex(name, index -> statement.setFloat(index, value));
    }

    /**
     * Binds double value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setDouble(String name, double value) throws SQLException {
        return setByIndex(name, index -> statement.setDouble(index, value));
    }

    /**
     * Binds {@link BigDecimal} value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setBigDecimal(String name, BigDecimal value) throws SQLException {
        return setByIndex(name, index -> statement.setBigDecimal(index, value));
    }

    /**
     * Binds byte array value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setBytes(String name, byte[] value) throws SQLException {
        return setByIndex(name, index -> statement.setBytes(index, value));
    }

    /**
     * Binds {@link Date} value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setDate(String name, Date value) throws SQLException {
        return setByIndex(name, index -> statement.setDate(index, value));
    }

    /**
     * Binds {@link Date} value with calendar to all occurrences of named parameter.
     */
    public NamedPreparedStatement setDate(String name, Date value, Calendar cal) throws SQLException {
        return setByIndex(name, index -> statement.setDate(index, value, cal));
    }

    /**
     * Binds {@link Time} value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setTime(String name, Time value) throws SQLException {
        return setByIndex(name, index -> statement.setTime(index, value));
    }

    /**
     * Binds {@link Time} value with calendar to all occurrences of named parameter.
     */
    public NamedPreparedStatement setTime(String name, Time value, Calendar cal) throws SQLException {
        return setByIndex(name, index -> statement.setTime(index, value, cal));
    }

    /**
     * Binds {@link Timestamp} value to all occurrences of named parameter.
     */
    public NamedPreparedStatement setTimestamp(String name, Timestamp value) throws SQLException {
        return setByIndex(name, index -> statement.setTimestamp(index, value));
    }

    /**
     * Binds {@link Timestamp} value with calendar to all occurrences of named parameter.
     */
    public NamedPreparedStatement setTimestamp(String name, Timestamp value, Calendar cal) throws SQLException {
        return setByIndex(name, index -> statement.setTimestamp(index, value, cal));
    }

    /**
     * Binds SQL NULL of generic type {@link Types#NULL}.
     */
    public NamedPreparedStatement setNull(String name) throws SQLException {
        return setNull(name, Types.NULL);
    }

    /**
     * Binds SQL NULL with explicit JDBC type.
     */
    public NamedPreparedStatement setNull(String name, int sqlType) throws SQLException {
        return setByIndex(name, index -> statement.setNull(index, sqlType));
    }

    /**
     * Binds SQL NULL with explicit JDBC type and database-specific type name.
     */
    public NamedPreparedStatement setNull(String name, int sqlType, String typeName) throws SQLException {
        return setByIndex(name, index -> statement.setNull(index, sqlType, typeName));
    }

    /**
     * Binds object with explicit JDBC SQL type.
     */
    public NamedPreparedStatement setObject(String name, Object value, int targetSqlType) throws SQLException {
        return setByIndex(name, index -> statement.setObject(index, value, targetSqlType));
    }

    /**
     * Binds object with explicit JDBC SQL type and scale/length.
     */
    public NamedPreparedStatement setObject(String name, Object value, int targetSqlType, int scaleOrLength) throws SQLException {
        return setByIndex(name, index -> statement.setObject(index, value, targetSqlType, scaleOrLength));
    }

    /**
     * Binds object with {@link SQLType}.
     */
    public NamedPreparedStatement setObject(String name, Object value, SQLType targetSqlType) throws SQLException {
        return setByIndex(name, index -> statement.setObject(index, value, targetSqlType));
    }

    /**
     * Binds object with {@link SQLType} and scale/length.
     */
    public NamedPreparedStatement setObject(String name, Object value, SQLType targetSqlType, int scaleOrLength) throws SQLException {
        return setByIndex(name, index -> statement.setObject(index, value, targetSqlType, scaleOrLength));
    }

    /**
     * Binds SQL array value.
     */
    public NamedPreparedStatement setArray(String name, Array value) throws SQLException {
        return setByIndex(name, index -> statement.setArray(index, value));
    }

    /**
     * Binds SQL reference value.
     */
    public NamedPreparedStatement setRef(String name, Ref value) throws SQLException {
        return setByIndex(name, index -> statement.setRef(index, value));
    }

    /**
     * Binds URL value.
     */
    public NamedPreparedStatement setURL(String name, URL value) throws SQLException {
        return setByIndex(name, index -> statement.setURL(index, value));
    }

    /**
     * Binds JDBC row id value.
     */
    public NamedPreparedStatement setRowId(String name, RowId value) throws SQLException {
        return setByIndex(name, index -> statement.setRowId(index, value));
    }

    /**
     * Binds SQLXML value.
     */
    public NamedPreparedStatement setSQLXML(String name, SQLXML value) throws SQLException {
        return setByIndex(name, index -> statement.setSQLXML(index, value));
    }

    /**
     * Binds {@link Blob} value.
     */
    public NamedPreparedStatement setBlob(String name, Blob value) throws SQLException {
        return setByIndex(name, index -> statement.setBlob(index, value));
    }

    /**
     * Binds blob binary stream value.
     */
    public NamedPreparedStatement setBlob(String name, InputStream inputStream) throws SQLException {
        return setByIndex(name, index -> statement.setBlob(index, inputStream));
    }

    /**
     * Binds blob binary stream value with explicit length.
     */
    public NamedPreparedStatement setBlob(String name, InputStream inputStream, long length) throws SQLException {
        return setByIndex(name, index -> statement.setBlob(index, inputStream, length));
    }

    /**
     * Binds {@link Clob} value.
     */
    public NamedPreparedStatement setClob(String name, Clob value) throws SQLException {
        return setByIndex(name, index -> statement.setClob(index, value));
    }

    /**
     * Binds character reader as CLOB.
     */
    public NamedPreparedStatement setClob(String name, Reader reader) throws SQLException {
        return setByIndex(name, index -> statement.setClob(index, reader));
    }

    /**
     * Binds character reader as CLOB with explicit length.
     */
    public NamedPreparedStatement setClob(String name, Reader reader, long length) throws SQLException {
        return setByIndex(name, index -> statement.setClob(index, reader, length));
    }

    /**
     * Binds {@link NClob} value.
     */
    public NamedPreparedStatement setNClob(String name, NClob value) throws SQLException {
        return setByIndex(name, index -> statement.setNClob(index, value));
    }

    /**
     * Binds reader as NCLOB.
     */
    public NamedPreparedStatement setNClob(String name, Reader reader) throws SQLException {
        return setByIndex(name, index -> statement.setNClob(index, reader));
    }

    /**
     * Binds reader as NCLOB with explicit length.
     */
    public NamedPreparedStatement setNClob(String name, Reader reader, long length) throws SQLException {
        return setByIndex(name, index -> statement.setNClob(index, reader, length));
    }

    /**
     * Binds ASCII stream.
     */
    public NamedPreparedStatement setAsciiStream(String name, InputStream value) throws SQLException {
        return setByIndex(name, index -> statement.setAsciiStream(index, value));
    }

    /**
     * Binds ASCII stream with int length.
     */
    public NamedPreparedStatement setAsciiStream(String name, InputStream value, int length) throws SQLException {
        return setByIndex(name, index -> statement.setAsciiStream(index, value, length));
    }

    /**
     * Binds ASCII stream with long length.
     */
    public NamedPreparedStatement setAsciiStream(String name, InputStream value, long length) throws SQLException {
        return setByIndex(name, index -> statement.setAsciiStream(index, value, length));
    }

    /**
     * Binds binary stream.
     */
    public NamedPreparedStatement setBinaryStream(String name, InputStream value) throws SQLException {
        return setByIndex(name, index -> statement.setBinaryStream(index, value));
    }

    /**
     * Binds binary stream with int length.
     */
    public NamedPreparedStatement setBinaryStream(String name, InputStream value, int length) throws SQLException {
        return setByIndex(name, index -> statement.setBinaryStream(index, value, length));
    }

    /**
     * Binds binary stream with long length.
     */
    public NamedPreparedStatement setBinaryStream(String name, InputStream value, long length) throws SQLException {
        return setByIndex(name, index -> statement.setBinaryStream(index, value, length));
    }

    /**
     * Binds character stream.
     */
    public NamedPreparedStatement setCharacterStream(String name, Reader reader) throws SQLException {
        return setByIndex(name, index -> statement.setCharacterStream(index, reader));
    }

    /**
     * Binds character stream with int length.
     */
    public NamedPreparedStatement setCharacterStream(String name, Reader reader, int length) throws SQLException {
        return setByIndex(name, index -> statement.setCharacterStream(index, reader, length));
    }

    /**
     * Binds character stream with long length.
     */
    public NamedPreparedStatement setCharacterStream(String name, Reader reader, long length) throws SQLException {
        return setByIndex(name, index -> statement.setCharacterStream(index, reader, length));
    }

    /**
     * Binds NCHAR character stream.
     */
    public NamedPreparedStatement setNCharacterStream(String name, Reader value) throws SQLException {
        return setByIndex(name, index -> statement.setNCharacterStream(index, value));
    }

    /**
     * Binds NCHAR character stream with explicit length.
     */
    public NamedPreparedStatement setNCharacterStream(String name, Reader value, long length) throws SQLException {
        return setByIndex(name, index -> statement.setNCharacterStream(index, value, length));
    }

    /**
     * Binds national character string value.
     */
    public NamedPreparedStatement setNString(String name, String value) throws SQLException {
        return setByIndex(name, index -> statement.setNString(index, value));
    }

    private NamedPreparedStatement setByIndex(String name, ThrowingConsumer<Integer> setter) throws SQLException {
        List<Integer> indexes = indexesFor(name);
        for (int index : indexes) {
            setter.accept(index);
        }
        boundValues.add(name);
        return this;
    }

    /**
     * Binds all entries from map using {@link #setObject(String, Object)}.
     */
    @SuppressWarnings("resource")
    public NamedPreparedStatement setAll(Map<String, ?> params) throws SQLException {
        if (params == null || params.isEmpty()) {
            return this;
        }
        for (Map.Entry<String, ?> e : params.entrySet()) {
            setObject(e.getKey(), e.getValue());
        }
        return this;
    }

    /**
     * Clears both wrapper binding state and underlying JDBC parameter values.
     */
    public void clearParameters() throws SQLException {
        boundValues.clear();
        statement.clearParameters();
    }

    /**
     * Executes query after ensuring that all named parameters are bound.
     */
    public ResultSet executeQuery() throws SQLException {
        ensureAllNamedParametersAreBound();
        return statement.executeQuery();
    }

    /**
     * Executes update after ensuring that all named parameters are bound.
     */
    public int executeUpdate() throws SQLException {
        ensureAllNamedParametersAreBound();
        return statement.executeUpdate();
    }

    /**
     * Executes statement after ensuring that all named parameters are bound.
     */
    public boolean execute() throws SQLException {
        ensureAllNamedParametersAreBound();
        return statement.execute();
    }

    /**
     * Adds current parameter set to batch after binding validation.
     */
    public void addBatch() throws SQLException {
        ensureAllNamedParametersAreBound();
        statement.addBatch();
    }

    /**
     * Executes JDBC batch on underlying statement.
     */
    public int[] executeBatch() throws SQLException {
        return statement.executeBatch();
    }

    /**
     * Returns underlying JDBC prepared statement.
     */
    public PreparedStatement unwrap() {
        return statement;
    }

    /**
     * Debug helper: names of parameters bound since last {@link #clearParameters()}.
     */
    public Set<String> getBoundValues() {
        return Collections.unmodifiableSet(boundValues);
    }

    /**
     * Returns parsed SQL transformed to JDBC placeholders.
     */
    public String getParsedSql() {
        return parsedSql.sql();
    }

    /**
     * Returns parameter names in positional order (including repeated occurrences).
     */
    public List<String> getParameterOrder() {
        return parsedSql.parameters().parameterNames();
    }

    private void ensureAllNamedParametersAreBound() {
        List<String> missing = new ArrayList<>();
        for (String name : namedIndexes.keySet()) {
            if (!boundValues.contains(name)) {
                missing.add(name);
            }
        }
        if (!missing.isEmpty()) {
            throw new IllegalStateException("Not all named parameters are bound: " + missing);
        }
    }

    private List<Integer> indexesFor(String name) {
        List<Integer> indexes = namedIndexes.get(name);
        if (indexes == null || indexes.isEmpty()) {
            throw new IllegalArgumentException("Unknown named parameter: " + name);
        }
        return indexes;
    }

    private static Map<String, List<Integer>> indexNamedParameters(ParsedParameters parameters) {
        if (parameters.positional()) {
            return Collections.emptyMap();
        }

        Map<String, List<Integer>> indexes = new LinkedHashMap<>();
        List<String> parameterNames = parameters.parameterNames();
        for (int i = 0; i < parameterNames.size(); i++) {
            String name = parameterNames.get(i);
            indexes.computeIfAbsent(name, key -> new ArrayList<>()).add(i + 1);
        }

        Map<String, List<Integer>> immutableIndexes = new LinkedHashMap<>();
        for (Map.Entry<String, List<Integer>> e : indexes.entrySet()) {
            immutableIndexes.put(e.getKey(), List.copyOf(e.getValue()));
        }
        return Collections.unmodifiableMap(immutableIndexes);
    }

    @Override
    public void close() throws SQLException {
        statement.close();
    }

    @FunctionalInterface
    private interface PreparedStatementCreator {
        PreparedStatement create(Connection connection, String sql) throws SQLException;
    }

    @FunctionalInterface
    private interface ThrowingConsumer<T> {
        void accept(T value) throws SQLException;
    }
}
